import { useState, useEffect, useRef } from 'react'
import { api, POLLING_CONFIG } from '../services/api'

function PlanDetailModal({ plan: initialPlan, onClose }) {
  const [plan, setPlan] = useState(initialPlan)
  const [loading, setLoading] = useState(
    initialPlan.status === 'pending' || initialPlan.status === 'processing'
  )
  const pollingTimeoutRef = useRef(null)
  const attemptRef = useRef(0)

  useEffect(() => {
    if (plan.status === 'pending' || plan.status === 'processing') {
      startPolling()
    }

    return () => {
      if (pollingTimeoutRef.current) {
        clearTimeout(pollingTimeoutRef.current)
      }
    }
  }, [])

  const startPolling = async () => {
    try {
      if (attemptRef.current >= POLLING_CONFIG.maxAttempts) {
        throw new Error('Polling timeout - task took too long')
      }

      const statusData = await api.getActionPlanStatus(plan.id)

      setPlan((prev) => ({ ...prev, status: statusData.status }))

      if (statusData.status === 'completed') {
        const fullPlan = await api.getActionPlan(plan.id)
        setPlan(fullPlan)
        setLoading(false)
        return
      }

      if (statusData.status === 'failed') {
        setPlan((prev) => ({
          ...prev,
          error_message: statusData.error_message || 'Failed to generate action plan',
        }))
        setLoading(false)
        return
      }

      const delayIndex = Math.min(
        attemptRef.current,
        POLLING_CONFIG.delays.length - 1
      )
      const delay = POLLING_CONFIG.delays[delayIndex]

      attemptRef.current += 1

      pollingTimeoutRef.current = setTimeout(() => {
        startPolling()
      }, delay)
    } catch (error) {
      console.error('Polling error:', error)
      alert('Error: ' + error.message)
      setLoading(false)
    }
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString)
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const handleDownload = async () => {
    if (plan.status !== 'completed' || !plan.plan_content) {
      alert('Plan is not ready for download')
      return
    }

    const customerLine = plan.customer
      ? `Customer: ${plan.customer.first_name} ${plan.customer.last_name} (${plan.customer.customer_id})`
      : ''

    const content = `
RETAIL ACTION PLAN
==================

Store: ${plan.store_name}
Location: ${plan.store_location}
${customerLine ? customerLine + '\n' : ''}Created: ${formatDate(plan.created_at)}
Status: ${plan.status}

ISSUE DESCRIPTION
-----------------
${plan.issue_description}

ACTION PLAN
-----------
${plan.plan_content}

---
Generated by Intelligent Retail Store Filter
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `action-plan-${plan.id}-${plan.store_name.replace(/\s+/g, '-')}.txt`
    document.body.appendChild(a)
    a.click()
    window.URL.revokeObjectURL(url)
    document.body.removeChild(a)
  }

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) {
      onClose()
    }
  }

  return (
    <div className="modal-overlay" onClick={handleOverlayClick}>
      <div className="modal-content">
        <div className="modal-header">
          <h2 className="modal-title">Action Plan Details</h2>
          <button className="close-btn" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="result-info">
          <p>
            <strong>Store:</strong> {plan.store_name}
          </p>
          <p>
            <strong>Location:</strong> {plan.store_location}
          </p>
          {plan.customer && (
            <p>
              <strong>Customer:</strong> {plan.customer.first_name} {plan.customer.last_name} ({plan.customer.customer_id}) | Phone: {plan.customer.phone}
            </p>
          )}
          <p>
            <strong>Issue:</strong> {plan.issue_description}
          </p>
          <p>
            <strong>Status:</strong>{' '}
            <span className={`status-badge status-${plan.status}`}>
              {plan.status}
            </span>
          </p>
          <p>
            <strong>Created:</strong> {formatDate(plan.created_at)}
          </p>
        </div>

        {loading && (
          <div className="loading">
            <div className="spinner"></div>
            <p>⏳ Generating action plan... This may take 10-30 seconds.</p>
          </div>
        )}

        {plan.status === 'completed' && plan.plan_content && (
          <>
            <h3 style={{ marginBottom: '16px', color: '#2c3e50', fontSize: '18px' }}>
              📋 Action Plan:
            </h3>
            <div className="plan-content">{plan.plan_content}</div>
            <button
              className="primary-button"
              style={{ marginTop: '24px' }}
              onClick={handleDownload}
            >
              Download Action Plan
            </button>
          </>
        )}

        {plan.status === 'failed' && (
          <div className="error-message">
            Error: {plan.error_message || 'Failed to generate action plan'}
          </div>
        )}
      </div>
    </div>
  )
}

export default PlanDetailModal
