import { useState, useEffect } from 'react'
import { api } from '../services/api'

const CATEGORIES = [
  { value: '', label: 'All Categories' },
  { value: 'FURNITURE', label: 'Furniture' },
  { value: 'ELECTRONICS', label: 'Electronics' },
  { value: 'CLOTHING', label: 'Clothing' },
]

function PlansList({ onPlanSelect, refreshTrigger }) {
  const [feedback, setFeedback] = useState([])
  const [stores, setStores] = useState([])
  const [loading, setLoading] = useState(true)
  
  // Filter states
  const [selectedStore, setSelectedStore] = useState('')
  const [selectedCategory, setSelectedCategory] = useState('')

  useEffect(() => {
    loadStores()
  }, [])

  useEffect(() => {
    loadFeedback()
  }, [refreshTrigger, selectedStore, selectedCategory])

  const loadStores = async () => {
    try {
      const data = await api.getStores()
      setStores([
        { store_id: '', name: 'All Stores' },
        ...data.stores
      ])
    } catch (error) {
      console.error('[PlansList] Error loading stores:', error)
    }
  }

  const loadFeedback = async () => {
    try {
      console.log('[PlansList] Loading feedback...', { 
        store: selectedStore || 'all', 
        category: selectedCategory || 'all' 
      })
      setLoading(true)
      
      const filters = {}
      if (selectedStore) filters.store_id = selectedStore
      if (selectedCategory) filters.category = selectedCategory
      
      const data = await api.listFeedback(filters)
      console.log('[PlansList] Loaded feedback:', data.count, 'items')
      setFeedback(data.feedback)
    } catch (error) {
      console.error('[PlansList] Error loading feedback:', error)
      alert('Error loading feedback: ' + error.message)
    } finally {
      setLoading(false)
    }
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString)
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const handleDownload = async (e, feedbackItem) => {
    e.stopPropagation()
    
    try {
      if (!feedbackItem.action_plan || feedbackItem.status !== 'completed' || !feedbackItem.action_plan.content) {
        alert('Action plan is not ready for download')
        return
      }

      const customerLine = feedbackItem.customer
        ? `Customer: ${feedbackItem.customer.first_name} ${feedbackItem.customer.last_name} (${feedbackItem.customer.customer_id})`
        : 'Customer: N/A'

      const content = `
RETAIL ACTION PLAN
==================

Store: ${feedbackItem.store_name} (${feedbackItem.store_id})
${customerLine}
Category: ${feedbackItem.category_code}
Feedback Date: ${formatDate(feedbackItem.created_at)}
Plan Created: ${formatDate(feedbackItem.action_plan.created_at)}
Status: ${feedbackItem.status}

ACTION PLAN
-----------
${feedbackItem.action_plan.content}

---
Generated by Intelligent Retail Store Filter
      `.trim()

      const blob = new Blob([content], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `action-plan-${feedbackItem.feedback_id}-${feedbackItem.store_id}-${feedbackItem.category_code}.txt`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (error) {
      alert('Error downloading plan: ' + error.message)
    }
  }

  const getCategoryLabel = (code) => {
    const category = CATEGORIES.find(c => c.value === code)
    return category ? category.label : code
  }

  if (loading) {
    return (
      <div className="card">
        <div className="loading">
          <div className="spinner"></div>
          <p>Loading plans...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="card">
      {/* Filter Bar */}
      <div className="filter-bar" style={{ 
        display: 'grid', 
        gridTemplateColumns: '1fr 1fr', 
        gap: '1rem', 
        marginBottom: '1.5rem',
        padding: '1rem',
        background: '#f8f9fa',
        borderRadius: '8px'
      }}>
        <div>
          <label style={{ 
            display: 'block', 
            marginBottom: '0.5rem', 
            fontSize: '0.875rem', 
            fontWeight: '500',
            color: '#495057'
          }}>
            Store
          </label>
          <select
            value={selectedStore}
            onChange={(e) => setSelectedStore(e.target.value)}
            style={{
              width: '100%',
              padding: '0.5rem',
              border: '1px solid #ced4da',
              borderRadius: '4px',
              fontSize: '0.875rem'
            }}
          >
            {stores.map((store) => (
              <option key={store.store_id} value={store.store_id}>
                {store.store_id ? `${store.name} (${store.store_id})` : store.name}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label style={{ 
            display: 'block', 
            marginBottom: '0.5rem', 
            fontSize: '0.875rem', 
            fontWeight: '500',
            color: '#495057'
          }}>
            Category
          </label>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            style={{
              width: '100%',
              padding: '0.5rem',
              border: '1px solid #ced4da',
              borderRadius: '4px',
              fontSize: '0.875rem'
            }}
          >
            {CATEGORIES.map((cat) => (
              <option key={cat.value} value={cat.value}>
                {cat.label}
              </option>
            ))}
          </select>
        </div>
      </div>

      {feedback.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">📋</div>
          <h3>No feedback found</h3>
          <p>
            {selectedStore || selectedCategory
              ? 'Try adjusting your filter criteria'
              : 'Submit feedback to generate action plans!'}
          </p>
        </div>
      ) : (
        <div className="plans-list">
          {feedback.map((item) => (
            <div
              key={item.feedback_id}
              className="plan-item"
              onClick={() => item.action_plan && onPlanSelect({
                id: item.action_plan.id,
                store_name: item.store_name,
                store_location: `${item.store_id} - ${item.category_code}`,
                issue_description: `Category: ${item.category_code}`,
                status: item.status,
                plan_content: item.action_plan.content,
                customer: item.customer,
                created_at: item.created_at
              })}
              style={{ cursor: item.action_plan ? 'pointer' : 'default' }}
            >
              <div className="plan-header">
                <div>
                  <div className="plan-title">
                    {item.store_name} ({item.store_id})
                  </div>
                  <div className="plan-meta">
                    {item.customer && (
                      <span>{item.customer.first_name} {item.customer.last_name} ({item.customer.customer_id}) • </span>
                    )}
                    {getCategoryLabel(item.category_code)} • {formatDate(item.created_at)}
                  </div>
                </div>
                <span className={`status-badge status-${item.status}`}>
                  {item.status}
                </span>
              </div>
              
              {item.action_plan && item.action_plan.content && (
                <div className="plan-description" style={{ 
                  maxHeight: '100px', 
                  overflow: 'hidden',
                  textOverflow: 'ellipsis'
                }}>
                  {item.action_plan.content.substring(0, 200)}...
                </div>
              )}
              
              <div className="plan-actions">
                {item.action_plan && (
                  <button
                    className="btn-small btn-view"
                    onClick={(e) => {
                      e.stopPropagation()
                      onPlanSelect({
                        id: item.action_plan.id,
                        store_name: item.store_name,
                        store_location: `${item.store_id} - ${item.category_code}`,
                        issue_description: `Category: ${item.category_code}`,
                        status: item.status,
                        plan_content: item.action_plan.content,
                        customer: item.customer,
                        created_at: item.created_at
                      })
                    }}
                  >
                    View Details
                  </button>
                )}
                {item.status === 'completed' && item.action_plan && (
                  <button
                    className="btn-small btn-download"
                    onClick={(e) => handleDownload(e, item)}
                  >
                    Download
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default PlansList
