import { useState, useEffect } from 'react'
import { api } from '../services/api'

function PlansList({ onPlanSelect, refreshTrigger }) {
  const [plans, setPlans] = useState([])
  const [filteredPlans, setFilteredPlans] = useState([])
  const [searchTerm, setSearchTerm] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadPlans()
  }, [refreshTrigger])

  useEffect(() => {
    const filtered = plans.filter(
      (plan) =>
        plan.store_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        plan.store_location.toLowerCase().includes(searchTerm.toLowerCase()) ||
        plan.issue_description.toLowerCase().includes(searchTerm.toLowerCase())
    )
    setFilteredPlans(filtered)
  }, [searchTerm, plans])

  const loadPlans = async () => {
    try {
      setLoading(true)
      const data = await api.listActionPlans()
      setPlans(data.action_plans)
      setFilteredPlans(data.action_plans)
    } catch (error) {
      console.error('Error loading plans:', error)
      alert('Error loading plans: ' + error.message)
    } finally {
      setLoading(false)
    }
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString)
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const handleDownload = async (e, planId) => {
    e.stopPropagation()
    
    try {
      const plan = await api.getActionPlan(planId)

      if (plan.status !== 'completed' || !plan.plan_content) {
        alert('Plan is not ready for download')
        return
      }

      const content = `
RETAIL ACTION PLAN
==================

Store: ${plan.store_name}
Location: ${plan.store_location}
Created: ${formatDate(plan.created_at)}
Status: ${plan.status}

ISSUE DESCRIPTION
-----------------
${plan.issue_description}

ACTION PLAN
-----------
${plan.plan_content}

---
Generated by Intelligent Retail Store Filter
      `.trim()

      const blob = new Blob([content], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `action-plan-${plan.id}-${plan.store_name.replace(/\s+/g, '-')}.txt`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (error) {
      alert('Error downloading plan: ' + error.message)
    }
  }

  if (loading) {
    return (
      <div className="card">
        <div className="loading">
          <div className="spinner"></div>
          <p>Loading plans...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="card">
      <div className="search-box">
        <input
          type="text"
          className="search-input"
          placeholder="Search by store name, location, or issue description..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {filteredPlans.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">📋</div>
          <h3>No action plans found</h3>
          <p>
            {searchTerm
              ? 'Try adjusting your search criteria'
              : 'Create your first action plan to get started!'}
          </p>
        </div>
      ) : (
        <div className="plans-list">
          {filteredPlans.map((plan) => (
            <div
              key={plan.id}
              className="plan-item"
              onClick={() => onPlanSelect(plan)}
            >
              <div className="plan-header">
                <div>
                  <div className="plan-title">{plan.store_name}</div>
                  <div className="plan-meta">
                    {plan.store_location} • {formatDate(plan.created_at)}
                  </div>
                </div>
                <span className={`status-badge status-${plan.status}`}>
                  {plan.status}
                </span>
              </div>
              <div className="plan-description">{plan.issue_description}</div>
              <div className="plan-actions">
                <button
                  className="btn-small btn-view"
                  onClick={(e) => {
                    e.stopPropagation()
                    onPlanSelect(plan)
                  }}
                >
                  View Details
                </button>
                {plan.status === 'completed' && (
                  <button
                    className="btn-small btn-download"
                    onClick={(e) => handleDownload(e, plan.id)}
                  >
                    Download
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default PlansList
