# Generated by Django 4.2.9 on 2026-03-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailops', '0004_add_store_to_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='retailops.feedback'),
        ),
    ]
