"""
Unit tests for customer duplicate detection (Option A).

Identity rule: first_name + last_name + phone → unique customer.
customer_id is auto-generated by the backend; frontend never provides it.

Scenarios covered:
1. No existing match → returns None
2. Exact match (all three fields) → returns existing customer
3. Any field differs → treated as a different customer (no warning)
4. create_customer_if_needed: auto-generates sequential customer_id (C001, C002…)
5. create_customer_if_needed: reuses existing on exact match
"""
import pytest
from retailops.models import Customer
from retailops.services import check_and_get_customer, create_customer_if_needed


@pytest.mark.unit
@pytest.mark.django_db
class TestCheckAndGetCustomer:

    def test_no_existing_customer_returns_none(self):
        result = check_and_get_customer('John', 'Doe', '1234567890')
        assert result is None

    def test_exact_match_returns_existing(self):
        existing = Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('John', 'Doe', '1234567890')
        assert result is not None
        assert result.id == existing.id

    def test_different_phone_returns_none(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('John', 'Doe', '9999999999')
        assert result is None

    def test_different_first_name_returns_none(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('Jane', 'Doe', '1234567890')
        assert result is None

    def test_different_last_name_returns_none(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('John', 'Smith', '1234567890')
        assert result is None

    def test_matching_is_case_sensitive(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('john', 'doe', '1234567890')
        assert result is None

    def test_no_warnings_or_exceptions_raised(self):
        """Different data never raises — just returns None (new customer)."""
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = check_and_get_customer('Jane', 'Smith', '9999999999')
        assert result is None


@pytest.mark.unit
@pytest.mark.django_db
class TestCreateCustomerIfNeeded:

    def test_creates_first_customer_with_c001(self):
        customer = create_customer_if_needed('John', 'Doe', '1234567890')
        assert customer.customer_id == 'C001'
        assert Customer.objects.count() == 1

    def test_creates_second_customer_with_c002(self):
        Customer.objects.create(
            customer_id='C001', first_name='Alice', last_name='A', phone='1111111111'
        )
        customer = create_customer_if_needed('Bob', 'B', '2222222222')
        assert customer.customer_id == 'C002'
        assert Customer.objects.count() == 2

    def test_reuses_existing_on_exact_match(self):
        existing = Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        result = create_customer_if_needed('John', 'Doe', '1234567890')
        assert result.id == existing.id
        assert Customer.objects.count() == 1

    def test_different_phone_creates_new_customer(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        new_customer = create_customer_if_needed('John', 'Doe', '9999999999')
        assert new_customer.customer_id == 'C002'
        assert Customer.objects.count() == 2

    def test_different_name_creates_new_customer(self):
        Customer.objects.create(
            customer_id='C001', first_name='John', last_name='Doe', phone='1234567890'
        )
        new_customer = create_customer_if_needed('Jane', 'Doe', '1234567890')
        assert new_customer.customer_id == 'C002'
        assert Customer.objects.count() == 2

    def test_stores_provided_name_and_phone(self):
        customer = create_customer_if_needed('Alice', 'Wong', '5551234567')
        assert customer.first_name == 'Alice'
        assert customer.last_name == 'Wong'
        assert customer.phone == '5551234567'
